polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('<int:pk>/results/', views.ResultsView.as_view(), name="results"),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('search/', views.search, name='search'),

]

votest_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    question_description = models.TextField(max_length=1000, default="Only description")
    pub_date = models.DateTimeField('data published')

    def __str__(self):
        return self.question_text

    @admin.display(boolean=True, ordering='pub_date', description="Published recently?")
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte= timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question' : question,
            'error_message' : "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def search(request):
    query_list = Question.objects.filter(pub_date__lte=timezone.now())
    if 'search' in request.GET:
        query = request.GET['search']
        if search:
            query_list = query_list.filter(question_text__icontains=query)

    context = {
        'questions' : query_list,
    }

    return render(request, 'polls/search.html', context)

polls/templates/polls/base.html
{% load static %}<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <!-- Meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'polls/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
        
        {% block stylesheet %}{% endblock stylesheet %}

        <title>Polls</title>
    </head>
    <body>
        {% block body %}
        <nav class="navbar navbar-dark bg-dark p-2">
            <a class="navbar-brand" href="{% url 'polls:index' %}">Polls</a>
            <form class="form-inline d-flex" action="{% url 'polls:search' %}">
                <input class="form-control" type="text" placeholder="Search" aria-label="Pesquisar" name="search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </nav>
        
        <!-- templates -->
        {% block content %}{% endblock content %}
        
        {% endblock body %}
        <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>    
    </body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class='container p-2'>
        <div class="row align-items-center">

            <!-- form detail-->
            <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
                <fieldset>
                    <!-- head question -->
                    <h1 class="mb-3 bd-text-purple-bright">{{ question.question_text }}</h1>
                    <p class="lead">{{ question.question_description }}</p>
                    
                    <!-- no selection error -->
                    {% if error_message %}
                        <div class="alert alert-danger" role="alert">
                            {{ error_message }}
                        </div>
                    {% endif %}

                    <!-- choices list -->
                    <ul class='list-group'>
                        {% for choice in question.choice_set.all %}
                            <li class="list-group-item list-group-item-warning">
                                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                            </li>
                        {% endfor %}
                    </ul>

                <!-- button vote -->
                <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-success m-2">Vote!</button>
                </div>
                </fieldset>
            </form>

        </div>
    </div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

    {% block content %}
    <div class="list-group test">

        {% if latest_question_list %}

            <!-- list of lastest questions -->
            {% for question in latest_question_list %}
                <a href="{% url 'polls:detail' question.id %}" class="list-group-item list-group-item-action flex-column align-items-start test">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ question.question_text }}</h5>
                    <small class="text-muted">{{ question.pub_date }}</small>
                </div>
                <p class="mb-1">{{ question.question_description }}</p>
                <!-- future implementation <small class="text-muted">most voted</small> -->
                </a>
            {% endfor %}

        {% else %}

            <!-- if list is empty -->
            <p>No polls are avaliable.</p>
        {% endif %}
    </div>
    {% endblock content %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

    {% block content %}
    <div class='container p-2'>
        <div class="row align-items-center">
            <h3>{{ question.question_text }}</h3>
            <div class='container'>
                <ul class="list-group list-group-flush">
                    {% for choice in question.choice_set.all %}
                        <li class='list-group-item list-group-item-warning'><p>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</p></li>
                    {% endfor %}
                </ul>
                <div class="d-flex justify-content-center m-2">
                    <a class='btn btn-success'href="{% url 'polls:detail' question.id %}"> Vote again? </a>
                </div>
            </div>
        </div>
    </div>
        
    {% endblock content %}

polls/templates/polls/search.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="list-group test">

    {% if questions %}

        <!-- list of search questions -->
        {% for question in questions %}
            <a href="{% url 'polls:detail' question.id %}" class="list-group-item list-group-item-action flex-column align-items-start test">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ question.question_text }}</h5>
                <small class="text-muted">{{ question.pub_date }}</small>
            </div>
            <p class="mb-1">{{ question.question_description }}</p>
             <!-- future implementation <small class="text-muted">most voted</small> -->
            </a>
        {% endfor %}

    {% else %}

        <!-- if list is empty -->
        <h3 class="alert">We couldn't find results.</h3>
    {% endif %}
</div>
{% endblock content %}